version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: yearly
  open-pull-requests-limit: 0
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: yearly
  open-pull-requests-limit: 0
